sudo: required
services:
  - docker
env:
  - IMAGE_NAME="runtimeverification/match-box"
before_install:
  - docker pull "$IMAGE_NAME"
  - docker ps -a
  - docker run --name match-box --volume "$PWD/":/root/ --rm -t -d "$IMAGE_NAME" 
script:
  - docker exec -it "$IMAGE_NAME" bash /root/rv.sh
  - docker container stop match-box