sudo: required
services:
  - docker
language: c
env:
  global:
    - IMAGE_NAME="runtimeverification/match-box"
    - CONTAINER_NAME="match-box"
before_install:
  - docker pull "$IMAGE_NAME"
  - docker ps -a
  - docker run --name "$CONTAINER_NAME" --volume "$PWD/":/repo/ --rm -t -d "$IMAGE_NAME" 
script:
  - docker exec -it "$CONTAINER_NAME" bash -c "cd /repo/; ls ;bash /repo/rv.sh"
  - docker container stop "$CONTAINER_NAME"